# Generated by Django 4.1.7 on 2023-02-15 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text="The author's first name (max. 50 characters)", max_length=50)),
                ('last_name', models.CharField(help_text="The author's last name (max. 50 characters)", max_length=50)),
                ('short_name', models.CharField(help_text='A short name to uniquely identify the author (max. 30 characters)', max_length=30, unique=True)),
                ('date_of_birth', models.DateField(help_text="The author's date of birth (YYYY-MM-DD)")),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="The work's full title (max. 100 characters)", max_length=100)),
                ('publication_date', models.IntegerField(help_text='The year in which the work was first published (YYYY; use negative numbers for B.C.)')),
                ('form', models.CharField(choices=[('NL', 'Novel'), ('PT', 'Poem'), ('DR', 'Drama'), ('ST', 'Short story'), ('NLA', 'Novella')], help_text='Select the appropriate literary form from the list of options', max_length=3)),
                ('wiki_link', models.URLField(blank=True, help_text='Link to the English-language Wikipedia page (max. 200 characters)', null=True, verbose_name='wikipedia link')),
                ('author', models.ForeignKey(help_text="The work's primary author", on_delete=django.db.models.deletion.PROTECT, to='literature.author')),
            ],
        ),
    ]
